---
name: Go format check

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/**"
    paths:
      - "**.go"
  pull_request: null

jobs:
  checkcode:
    name: "gofmt check"
    runs-on: ubuntu-latest
    steps:
      - uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: "./api"
          gofmt-flags: "-l -d"
